apiVersion: v1
kind: Pod
metadata:
  name: test-kuard1
spec:
  containers:
    - name: ct-kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      ports:
        - name: web
          containerPort: 8060
          protocol: TCP